import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const site = join(dirname(fileURLToPath(import.meta.url)), '..');
export const origin = 'https://rminte.com';
export const pages = JSON.parse(readFileSync(join(site, 'scripts/seo-metadata.json'), 'utf8'));
const escape = value => String(value).replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const pairAttributes = pair => `data-zh="${escape(pair.zh)}" data-en="${escape(pair.en)}"`;

export function seoHead(key) {
  const page = pages[key];
  const url = origin + page.path;
  const image = origin + (key === 'gallery' ? '/assets/gallery/DSC00043.jpg' : '/assets/images/img4.png');
  const organization = `${origin}/#organization`;
  const website = `${origin}/#website`;
  const graph = [{ '@type': 'WebPage', '@id': `${url}#webpage`, url, isPartOf: { '@id': website } }];
  if (key === 'home') graph.push(
    { '@type': 'Organization', '@id': organization, name: 'RMinte', legalName: '泛灵（成都）人工智能科技有限公司', url: `${origin}/`, logo: `${origin}/assets/images/logo-white.svg` },
    { '@type': 'WebSite', '@id': website, name: 'RMinte', url: `${origin}/`, publisher: { '@id': organization } },
    { '@type': 'Product', '@id': `${origin}/#rm-01`, name: 'RM-01', url, image, brand: { '@type': 'Brand', name: 'RMinte' }, manufacturer: { '@id': organization } }
  );
  return `<!-- SEO: generated by scripts/seo.mjs; edit scripts/seo-metadata.json -->
  <title ${pairAttributes(page.title)}>${escape(page.title.zh)}</title>
  <meta name="description" content="${escape(page.description.zh)}" data-i18n-attr="content" ${pairAttributes(page.description)}>
  <link rel="canonical" href="${url}">
  <meta property="og:title" content="${escape(page.title.zh)}" data-i18n-attr="content" ${pairAttributes(page.title)}>
  <meta property="og:description" content="${escape(page.description.zh)}" data-i18n-attr="content" ${pairAttributes(page.description)}>
  <meta property="og:type" content="website">
  <meta property="og:url" content="${url}">
  <meta property="og:image" content="${image}">
  <script type="application/ld+json">${JSON.stringify({ '@context': 'https://schema.org', '@graph': graph }).replaceAll('<', '\\u003c')}</script>
  <!-- /SEO -->`;
}

export function buildSeo() {
  for (const [key, page] of Object.entries(pages)) {
    const file = join(site, page.file);
    const html = readFileSync(file, 'utf8');
    const updated = html.replace(/<head>([\s\S]*?)<\/head>/, (_, head) => {
      if (head.includes('<!-- SEO:')) return `<head>${head.replace(/<!-- SEO:[\s\S]*?<!-- \/SEO -->/, seoHead(key))}</head>`;
      head = head.replace(/\s*<title\b[^>]*>[\s\S]*?<\/title>/g, '')
        .replace(/\s*<meta\b[^>]*(?:name="description"|property="og:[^"]+")[^>]*>/g, '')
        .replace(/\s*<link\b[^>]*rel="canonical"[^>]*>/g, '');
      return `<head>${head}\n  ${seoHead(key)}\n</head>`;
    });
    writeFileSync(file, updated);
  }
  // These images already belong to the JavaScript gallery. Discover them without adding requests or DOM nodes.
  const gallery = readFileSync(join(site, 'assets/gallery.js'), 'utf8');
  const images = [...gallery.matchAll(/src: '\.\.\/(assets\/gallery\/[^']+)'/g)].map(match => `${origin}/${match[1]}`);
  const urls = Object.entries(pages).map(([key, page]) => `  <url><loc>${origin}${page.path}</loc>${key === 'gallery' ? images.map(image => `<image:image><image:loc>${escape(image)}</image:loc></image:image>`).join('') : ''}</url>`);
  writeFileSync(join(site, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n${urls.join('\n')}\n</urlset>\n`);
  writeFileSync(join(site, 'robots.txt'), `User-agent: *\nAllow: /\n\nSitemap: ${origin}/sitemap.xml\n`);
  // An empty error response disables Pages' implicit SPA fallback; it is not a content page.
  writeFileSync(join(site, '404.html'), '');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  buildSeo();
  console.log(`Generated SEO metadata for ${Object.keys(pages).length} pages, robots.txt and the image sitemap.`);
}
